import Head from "next/head";
import {ProgressBar} from "../../components/progress-bar";
import {ProgressSpinner} from "../../components/progress-spinner";

export default function Component() {
    return (
        <>
            <Head>
                <title>影遁 | 组件</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>
            <main>
                <section id="component-cta">
                    <div className="app-container">
                        <ProgressSpinner />
                        <ProgressBar />
                    </div>
                </section>
            </main>
        </>
    )
}