import Head from "next/head";
import React from "react";

export default function Labs() {

    return (
        <>
            <Head>
                <title>影遁 | 实验室</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>
            <main>
            </main>
        </>
    )
}
